apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
